import { v2 as cloudinary } from 'cloudinary';
import fs from 'fs'

cloudinary.config({ 
    cloud_name: process.env.CLOUD_NAME, 
    api_key: process.env.CLOUD_KEY,
    api_secret: process.env.CLOUD_SECRET
});

const uploadOnCloud=async(localPath)=>{
    try {
        if(!localPath){
            console.log("localpath is required to upload image")
        }
        const response=await cloudinary.uploader
        .upload(
            localPath,{
                fetch_format: 'auto',       
            }
        )
        //unlinking the localpath generated by multer after saving image on cloud
        fs.unlinkSync(localPath)
        return response;
    } catch (error) {
        //unlinking path so that we ask again from user if upload fails
        fs.unlinkSync(localPath)
        console.log("failed to upload try again");
        return null;
    }
}

export {uploadOnCloud}