import { v2 as cloudinary } from 'cloudinary';
import fs from 'fs'

cloudinary.config({ 
    cloud_name: 'dqzbkjg6f', 
    api_key: '893594224553534', 
    api_secret: '<your_api_secret>' // Click 'View API Keys' above to copy your API secret
});

const uploadOnCloud=async(localPath)=>{
    try {
        if(!localPath){
            console.log("localpath is required to upload image")
        }
        const response=await cloudinary.uploader
        .upload(
            localPath,{
                fetch_format: 'auto',       
            }
        )
        //unlinking the localpath generated by multer after saving image on cloud
        fs.unlinkSync(localPath)
        return response;
    } catch (error) {
        //unlinking path so that we ask again from user if upload fails
        fs.unlinkSync(localPath)
        console.log("failed to upload try again");
        return null;
    }
}


return {uploadOnCloud}